# Pandas replace() Values (Part - 6)

In [1]:
import pandas as pd

In [3]:
df =pd.read_csv('E:\\ML\\annualenterprise.csv')
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [4]:
df.replace(to_replace= '2013' ,value = "2000")

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [5]:
df.replace(to_replace= 2013 ,value = 2000)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [6]:
df.replace(2000,2013)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [7]:
df.replace([2013,2020],2000)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2000,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2000,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2000,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2000,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2000,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2000,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [8]:
df.replace('[A-Za-z]',0)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [9]:
df.replace('[A-Za-z]',0 , regex = True)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,0,99999,0,0,0,0,0,"7,33,258",0
1,2020,0,99999,0,0,NaN,0,0,"6,60,630",0
2,2020,0,NaN,0,0,NaN,0,0,"54,342",0
3,2020,0,NaN,0,0,NaN,0,0,"18,285",0
4,2020,0,NaN,0,0,NaN,0,0,"6,54,872",0
...,...,...,...,...,...,...,...,...,...,...
37075,2013,0,0,0,0,0,0,0,52,0
37076,2013,0,0,0,0,0,0,0,40,0
37077,2013,0,0,0,0,0,0,0,12,0
37078,2013,0,0,0,0,0,0,0,5,0
37079,2013,0,0,0,0,0,0,0,46,0

In [10]:
df.replace({'Industry_name_NZSIOC': '[A-Za-z]'}, 0, regex = True)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,0,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,0,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,0,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,0,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,0,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,0,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,0,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,0,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,0,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,0,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [11]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [14]:
df.replace('All industries',method = 'bfill')

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,Horticulture and Fruit Growing,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,Horticulture and Fruit Growing,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,Horticulture and Fruit Growing,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,Horticulture and Fruit Growing,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,Horticulture and Fruit Growing,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [15]:
df.replace(0, method = 'bfill' ,limit =2)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [16]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"7,33,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),NaN,"Sales, government funding, grants and subsidies",Financial performance,"6,60,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,NaN,All industries,Dollars (millions),NaN,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,NaN,All industries,Dollars (millions),NaN,Total expenditure,Financial performance,"6,54,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."